// Generated by copybook-ts from customer.cpy. Do not edit: change the copybook and
// regenerate. The layout below is frozen at build time, so the copybook is not
// needed at runtime.

import { layoutFrom, decodeRecord, decodeFile } from '../../src/index.js';
import type { DecodeOptions, Item, Layout } from '../../src/index.js';

export interface CustomerMaster {
  'CUST-ID': string;
  'CUST-NAME': string;
  BALANCE: string;
  'ORDER-COUNT': string;
  RATE: number;
  'CUSTOMER-MASTER.BILLING.ADDRESS-LINE': string;
  'CUSTOMER-MASTER.SHIPPING.ADDRESS-LINE': string;
}

const root: Item = {
  level: 1,
  name: 'CUSTOMER-MASTER',
  offset: 0,
  size: 56,
  children: [
    {
      level: 5,
      name: 'CUST-ID',
      field: { pic: '9(5)', category: 'numeric', usage: 'DISPLAY', digits: 5, scale: 0, signed: false, signPosition: 'trailing', size: 5 },
      offset: 0,
      size: 5,
      children: [],
    },
    {
      level: 5,
      name: 'CUST-NAME',
      field: { pic: 'X(20)', category: 'alphanumeric', usage: 'DISPLAY', digits: 0, scale: 0, signed: false, signPosition: 'trailing', size: 20 },
      offset: 5,
      size: 20,
      children: [],
    },
    {
      level: 5,
      name: 'BALANCE',
      field: { pic: 'S9(7)V99', category: 'numeric', usage: 'COMP-3', digits: 9, scale: 2, signed: true, signPosition: 'trailing', size: 5 },
      offset: 25,
      size: 5,
      children: [],
    },
    {
      level: 5,
      name: 'ORDER-COUNT',
      field: { pic: 'S9(4)', category: 'numeric', usage: 'BINARY', digits: 4, scale: 0, signed: true, signPosition: 'trailing', size: 2 },
      offset: 30,
      size: 2,
      children: [],
    },
    {
      level: 5,
      name: 'RATE',
      field: { pic: 'S9(4)V99', category: 'numeric', usage: 'COMP-1', digits: 6, scale: 2, signed: true, signPosition: 'trailing', size: 4 },
      offset: 32,
      size: 4,
      children: [],
    },
    {
      level: 5,
      name: 'BILLING',
      offset: 36,
      size: 10,
      children: [
        {
          level: 10,
          name: 'ADDRESS-LINE',
          field: { pic: 'X(10)', category: 'alphanumeric', usage: 'DISPLAY', digits: 0, scale: 0, signed: false, signPosition: 'trailing', size: 10 },
          offset: 36,
          size: 10,
          children: [],
        },
      ],
    },
    {
      level: 5,
      name: 'SHIPPING',
      offset: 46,
      size: 10,
      children: [
        {
          level: 10,
          name: 'ADDRESS-LINE',
          field: { pic: 'X(10)', category: 'alphanumeric', usage: 'DISPLAY', digits: 0, scale: 0, signed: false, signPosition: 'trailing', size: 10 },
          offset: 46,
          size: 10,
          children: [],
        },
      ],
    },
  ],
};

/** 56 bytes per record. */
export const CUSTOMER_MASTER_LAYOUT: Layout = layoutFrom(root);

/** Decodes exactly one record. */
export function decodeCustomerMaster(buf: Uint8Array, options: DecodeOptions): CustomerMaster {
  return decodeRecord(buf, CUSTOMER_MASTER_LAYOUT, options) as unknown as CustomerMaster;
}

/** Decodes every record in a fixed-length file. */
export function* decodeCustomerMasterFile(
  buf: Uint8Array,
  options: DecodeOptions,
): Generator<CustomerMaster> {
  for (const record of decodeFile(buf, CUSTOMER_MASTER_LAYOUT, options)) {
    yield record as unknown as CustomerMaster;
  }
}
