// Generated by copybook-ts from order.cpy. Do not edit: change the copybook and
// regenerate. The layout below is frozen at build time, so the copybook is not
// needed at runtime.

import { layoutFrom, decodeRecord, decodeFile } from '../../src/index.js';
import type { DecodeOptions, Item, Layout } from '../../src/index.js';

export interface OrderRecord {
  'ORDER-ID': string;
  'LINE-COUNT': string;
  LINES: {
    'ITEM-CODE': string;
    QTY: string;
  }[];
  TOTAL: string;
}

const root: Item = {
  level: 1,
  name: 'ORDER-RECORD',
  offset: 0,
  size: 26,
  children: [
    {
      level: 5,
      name: 'ORDER-ID',
      field: { pic: '9(5)', category: 'numeric', usage: 'DISPLAY', digits: 5, scale: 0, signed: false, signPosition: 'trailing', size: 5 },
      offset: 0,
      size: 5,
      children: [],
    },
    {
      level: 5,
      name: 'LINE-COUNT',
      field: { pic: '9(2)', category: 'numeric', usage: 'DISPLAY', digits: 2, scale: 0, signed: false, signPosition: 'trailing', size: 2 },
      offset: 5,
      size: 2,
      children: [],
    },
    {
      level: 5,
      name: 'LINES',
      occurs: { min: 1, max: 3, dependingOn: 'LINE-COUNT' },
      offset: 7,
      size: 5,
      children: [
        {
          level: 10,
          name: 'ITEM-CODE',
          field: { pic: 'X(3)', category: 'alphanumeric', usage: 'DISPLAY', digits: 0, scale: 0, signed: false, signPosition: 'trailing', size: 3 },
          offset: 7,
          size: 3,
          children: [],
        },
        {
          level: 10,
          name: 'QTY',
          field: { pic: 'S9(3)', category: 'numeric', usage: 'COMP-3', digits: 3, scale: 0, signed: true, signPosition: 'trailing', size: 2 },
          offset: 10,
          size: 2,
          children: [],
        },
      ],
    },
    {
      level: 5,
      name: 'TOTAL',
      field: { pic: 'S9(5)V99', category: 'numeric', usage: 'COMP-3', digits: 7, scale: 2, signed: true, signPosition: 'trailing', size: 4 },
      offset: 22,
      size: 4,
      children: [],
    },
  ],
};

/** Up to 26 bytes per record: the tables vary in length. */
export const ORDER_RECORD_LAYOUT: Layout = layoutFrom(root);

/** Decodes exactly one record. */
export function decodeOrderRecord(buf: Uint8Array, options: DecodeOptions): OrderRecord {
  return decodeRecord(buf, ORDER_RECORD_LAYOUT, options) as unknown as OrderRecord;
}

/** Decodes every record in the file. */
export function* decodeOrderRecordFile(
  buf: Uint8Array,
  options: DecodeOptions,
): Generator<OrderRecord> {
  for (const record of decodeFile(buf, ORDER_RECORD_LAYOUT, options)) {
    yield record as unknown as OrderRecord;
  }
}
